name: DiscordChatter
version: 1.1.0-pre1
main: me.tsukuba.soho.plugin.chat.DiscordChatter
api-version: '1.18'
author: frodo821
description: Minecraft multiplayer server management utility over discord server
