name: DiscordChatter
version: 0.0.4
main: me.tsukuba.soho.plugin.chat.DiscordChatter
api-version: '1.18'
author: frodo821
description: Minecraft multiplayer server management utility over discord server
