package me.tsukuba.soho.plugin.chat.map

import org.bukkit.Material
import org.bukkit.Color
import org.bukkit.configuration.ConfigurationSection


fun initializeColorMap(config: ConfigurationSection) {
    val maps = config.getConfigurationSection("maps") ?: config.createSection("maps")
    val colors = maps.getConfigurationSection("colors") ?: maps.createSection("colors")

    val defaultColors = mapOf(
        Material.GRASS.key.toString() to Color.fromRGB(49, 101, 25),
        Material.TALL_GRASS.key.toString() to Color.fromRGB(49, 101, 25),
        Material.COBBLESTONE.key.toString() to Color.fromRGB(130, 130, 130),
        Material.COBBLESTONE_SLAB.key.toString() to Color.fromRGB(130, 130, 130),
        Material.FURNACE.key.toString() to Color.fromRGB(130, 130, 130),
        Material.STONE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.STONE_SLAB.key.toString() to Color.fromRGB(117, 117, 117),
        Material.IRON_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.GOLD_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.REDSTONE_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.DIAMOND_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.COAL_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.EMERALD_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.LAPIS_ORE.key.toString() to Color.fromRGB(117, 117, 117),
        Material.IRON_BLOCK.key.toString() to Color.fromRGB(236, 236, 236),
        Material.GOLD_BLOCK.key.toString() to Color.fromRGB(243, 223, 75),
        Material.REDSTONE_BLOCK.key.toString() to Color.fromRGB(196, 25, 16),
        Material.DIAMOND_BLOCK.key.toString() to Color.fromRGB(95, 233, 217),
        Material.COAL_BLOCK.key.toString() to Color.fromRGB(19, 19, 19),
        Material.EMERALD_BLOCK.key.toString() to Color.fromRGB(71, 213, 105),
        Material.LAPIS_BLOCK.key.toString() to Color.fromRGB(42, 80, 139),
        Material.WATER.key.toString() to Color.fromRGB(67, 101, 165),
        Material.SEAGRASS.key.toString() to Color.fromRGB(67, 101, 165),
        Material.BUBBLE_COLUMN.key.toString() to Color.fromRGB(67, 101, 165),
        Material.TALL_SEAGRASS.key.toString() to Color.fromRGB(67, 101, 165),
        Material.KELP.key.toString() to Color.fromRGB(67, 101, 165),
        Material.GRASS_BLOCK.key.toString() to Color.fromRGB(82, 129, 69),
        Material.DIRT.key.toString() to Color.fromRGB(168, 120, 83),
        Material.SAND.key.toString() to Color.fromRGB(222, 215, 172),
        Material.SANDSTONE.key.toString() to Color.fromRGB(213, 207, 162),
        Material.ACACIA_LEAVES.key.toString() to Color.fromRGB(73, 181, 24),
        Material.BIRCH_LEAVES.key.toString() to Color.fromRGB(114, 149, 76),
        Material.DARK_OAK_LEAVES.key.toString() to Color.fromRGB(72, 186, 18),
        Material.JUNGLE_LEAVES.key.toString() to Color.fromRGB(74, 185, 25),
        Material.OAK_LEAVES.key.toString() to Color.fromRGB(73, 183, 24),
        Material.SPRUCE_LEAVES.key.toString() to Color.fromRGB(55, 91, 56),
        Material.GRASS.key.toString() to Color.fromRGB(170, 148, 89),
        Material.COARSE_DIRT.key.toString() to Color.fromRGB(104, 75, 51),
        Material.ANDESITE.key.toString() to Color.fromRGB(136, 136, 138),
        Material.DIORITE.key.toString() to Color.fromRGB(181, 181, 181),
        Material.DEAD_BUSH.key.toString() to Color.fromRGB(144, 97, 39),
        Material.CACTUS.key.toString() to Color.fromRGB(76, 107, 35),
        Material.DANDELION.key.toString() to Color.fromRGB(247, 229, 77),
        Material.POPPY.key.toString() to Color.fromRGB(230, 47, 43),
        Material.CORNFLOWER.key.toString() to Color.fromRGB(70, 106, 235),
        Material.AZURE_BLUET.key.toString() to Color.fromRGB(210, 215, 223),
        Material.OXEYE_DAISY.key.toString() to Color.fromRGB(187, 188, 189),
        Material.LAVA.key.toString() to Color.fromRGB(211, 124, 40),
        Material.GRANITE.key.toString() to Color.fromRGB(156, 111, 91),
        Material.REDSTONE_LAMP.key.toString() to Color.fromRGB(123, 73, 33),
        Material.GRAVEL.key.toString() to Color.fromRGB(139, 135, 134),
        Material.SPRUCE_LOG.key.toString() to Color.fromRGB(48, 34, 25),
        Material.OAK_LOG.key.toString() to Color.fromRGB(58, 35, 9),
        Material.BIRCH_LOG.key.toString() to Color.fromRGB(196, 195, 193),
        Material.JUNGLE_LOG.key.toString() to Color.fromRGB(89, 76, 37),
        Material.ACACIA_LOG.key.toString() to Color.fromRGB(95, 95, 85),
        Material.DARK_OAK_LOG.key.toString() to Color.fromRGB(35, 27, 16),
        Material.SPRUCE_PLANKS.key.toString() to Color.fromRGB(100, 78, 47),
        Material.OAK_PLANKS.key.toString() to Color.fromRGB(172, 140, 88),
        Material.BIRCH_PLANKS.key.toString() to Color.fromRGB(202, 185, 131),
        Material.JUNGLE_PLANKS.key.toString() to Color.fromRGB(172, 124, 89),
        Material.ACACIA_PLANKS.key.toString() to Color.fromRGB(178, 102, 60),
        Material.DARK_OAK_PLANKS.key.toString() to Color.fromRGB(62, 41, 18),
        Material.SPRUCE_FENCE.key.toString() to Color.fromRGB(100, 78, 47),
        Material.OAK_FENCE.key.toString() to Color.fromRGB(172, 140, 88),
        Material.BIRCH_FENCE.key.toString() to Color.fromRGB(202, 185, 131),
        Material.JUNGLE_FENCE.key.toString() to Color.fromRGB(172, 124, 89),
        Material.ACACIA_FENCE.key.toString() to Color.fromRGB(178, 102, 60),
        Material.DARK_OAK_FENCE.key.toString() to Color.fromRGB(62, 41, 18),
        Material.SPRUCE_STAIRS.key.toString() to Color.fromRGB(100, 78, 47),
        Material.OAK_STAIRS.key.toString() to Color.fromRGB(172, 140, 88),
        Material.BIRCH_STAIRS.key.toString() to Color.fromRGB(202, 185, 131),
        Material.JUNGLE_STAIRS.key.toString() to Color.fromRGB(172, 124, 89),
        Material.ACACIA_STAIRS.key.toString() to Color.fromRGB(178, 102, 60),
        Material.DARK_OAK_STAIRS.key.toString() to Color.fromRGB(62, 41, 18),
        Material.SPRUCE_SLAB.key.toString() to Color.fromRGB(100, 78, 47),
        Material.OAK_SLAB.key.toString() to Color.fromRGB(172, 140, 88),
        Material.BIRCH_SLAB.key.toString() to Color.fromRGB(202, 185, 131),
        Material.JUNGLE_SLAB.key.toString() to Color.fromRGB(172, 124, 89),
        Material.ACACIA_SLAB.key.toString() to Color.fromRGB(178, 102, 60),
        Material.DARK_OAK_SLAB.key.toString() to Color.fromRGB(62, 41, 18),
        Material.CRAFTING_TABLE.key.toString() to Color.fromRGB(172, 140, 88),
        Material.BOOKSHELF.key.toString() to Color.fromRGB(172, 140, 88),
        Material.SUGAR_CANE.key.toString() to Color.fromRGB(71, 139, 42),
        Material.BEDROCK.key.toString() to Color.fromRGB(47, 47, 47),
        Material.TORCH.key.toString() to Color.fromRGB(206, 173, 26),
        Material.PUMPKIN.key.toString() to Color.fromRGB(222, 141, 28),
        Material.CARVED_PUMPKIN.key.toString() to Color.fromRGB(222, 141, 28),
        Material.JACK_O_LANTERN.key.toString() to Color.fromRGB(222, 141, 28),
        Material.TNT.key.toString() to Color.fromRGB(203, 49, 26),
        Material.BLACK_WOOL.key.toString() to Color.fromRGB(6, 7, 12),
        Material.WHITE_WOOL.key.toString() to Color.fromRGB(225, 226, 228),
        Material.BLUE_WOOL.key.toString() to Color.fromRGB(45, 50, 145),
        Material.BROWN_WOOL.key.toString() to Color.fromRGB(105, 70, 39),
        Material.CYAN_WOOL.key.toString() to Color.fromRGB(21, 139, 145),
        Material.GRAY_WOOL.key.toString() to Color.fromRGB(64, 67, 72),
        Material.GREEN_WOOL.key.toString() to Color.fromRGB(83, 108, 20),
        Material.LIGHT_BLUE_WOOL.key.toString() to Color.fromRGB(121, 148, 202),
        Material.LIGHT_GRAY_WOOL.key.toString() to Color.fromRGB(164, 168, 169),
        Material.LIME_WOOL.key.toString() to Color.fromRGB(122, 198, 38),
        Material.MAGENTA_WOOL.key.toString() to Color.fromRGB(188, 66, 179),
        Material.ORANGE_WOOL.key.toString() to Color.fromRGB(240, 125, 30),
        Material.PINK_WOOL.key.toString() to Color.fromRGB(242, 148, 177),
        Material.PURPLE_WOOL.key.toString() to Color.fromRGB(129, 65, 182),
        Material.RED_WOOL.key.toString() to Color.fromRGB(155, 53, 49),
        Material.YELLOW_WOOL.key.toString() to Color.fromRGB(195, 182, 47),
        Material.BLACK_BANNER.key.toString() to Color.fromRGB(6, 7, 12),
        Material.WHITE_BANNER.key.toString() to Color.fromRGB(225, 226, 228),
        Material.BLUE_BANNER.key.toString() to Color.fromRGB(45, 50, 145),
        Material.BROWN_BANNER.key.toString() to Color.fromRGB(105, 70, 39),
        Material.CYAN_BANNER.key.toString() to Color.fromRGB(21, 139, 145),
        Material.GRAY_BANNER.key.toString() to Color.fromRGB(64, 67, 72),
        Material.GREEN_BANNER.key.toString() to Color.fromRGB(83, 108, 20),
        Material.LIGHT_BLUE_BANNER.key.toString() to Color.fromRGB(121, 148, 202),
        Material.LIGHT_GRAY_BANNER.key.toString() to Color.fromRGB(164, 168, 169),
        Material.LIME_BANNER.key.toString() to Color.fromRGB(122, 198, 38),
        Material.MAGENTA_BANNER.key.toString() to Color.fromRGB(188, 66, 179),
        Material.ORANGE_BANNER.key.toString() to Color.fromRGB(240, 125, 30),
        Material.PINK_BANNER.key.toString() to Color.fromRGB(242, 148, 177),
        Material.PURPLE_BANNER.key.toString() to Color.fromRGB(129, 65, 182),
        Material.RED_BANNER.key.toString() to Color.fromRGB(155, 53, 49),
        Material.YELLOW_BANNER.key.toString() to Color.fromRGB(195, 182, 47),
        Material.BLACK_WALL_BANNER.key.toString() to Color.fromRGB(6, 7, 12),
        Material.WHITE_WALL_BANNER.key.toString() to Color.fromRGB(225, 226, 228),
        Material.BLUE_WALL_BANNER.key.toString() to Color.fromRGB(45, 50, 145),
        Material.BROWN_WALL_BANNER.key.toString() to Color.fromRGB(105, 70, 39),
        Material.CYAN_WALL_BANNER.key.toString() to Color.fromRGB(21, 139, 145),
        Material.GRAY_WALL_BANNER.key.toString() to Color.fromRGB(64, 67, 72),
        Material.GREEN_WALL_BANNER.key.toString() to Color.fromRGB(83, 108, 20),
        Material.LIGHT_BLUE_WALL_BANNER.key.toString() to Color.fromRGB(121, 148, 202),
        Material.LIGHT_GRAY_WALL_BANNER.key.toString() to Color.fromRGB(164, 168, 169),
        Material.LIME_WALL_BANNER.key.toString() to Color.fromRGB(122, 198, 38),
        Material.MAGENTA_WALL_BANNER.key.toString() to Color.fromRGB(188, 66, 179),
        Material.ORANGE_WALL_BANNER.key.toString() to Color.fromRGB(240, 125, 30),
        Material.PINK_WALL_BANNER.key.toString() to Color.fromRGB(242, 148, 177),
        Material.PURPLE_WALL_BANNER.key.toString() to Color.fromRGB(129, 65, 182),
        Material.RED_WALL_BANNER.key.toString() to Color.fromRGB(155, 53, 49),
        Material.YELLOW_WALL_BANNER.key.toString() to Color.fromRGB(195, 182, 47),
        Material.BLACK_CONCRETE.key.toString() to Color.fromRGB(7, 9, 14),
        Material.WHITE_CONCRETE.key.toString() to Color.fromRGB(199, 202, 207),
        Material.BLUE_CONCRETE.key.toString() to Color.fromRGB(42, 44, 133),
        Material.BROWN_CONCRETE.key.toString() to Color.fromRGB(91, 57, 30),
        Material.CYAN_CONCRETE.key.toString() to Color.fromRGB(20, 113, 129),
        Material.GRAY_CONCRETE.key.toString() to Color.fromRGB(118, 119, 110),
        Material.GREEN_CONCRETE.key.toString() to Color.fromRGB(88, 156, 25),
        Material.LIGHT_BLUE_CONCRETE.key.toString() to Color.fromRGB(33, 130, 190),
        Material.LIGHT_GRAY_CONCRETE.key.toString() to Color.fromRGB(195, 203, 206),
        Material.LIME_CONCRETE.key.toString() to Color.fromRGB(90, 162, 23),
        Material.MAGENTA_CONCRETE.key.toString() to Color.fromRGB(162, 47, 152),
        Material.ORANGE_CONCRETE.key.toString() to Color.fromRGB(207, 81, 1),
        Material.PINK_CONCRETE.key.toString() to Color.fromRGB(205, 95, 138),
        Material.PURPLE_CONCRETE.key.toString() to Color.fromRGB(155, 45, 145),
        Material.RED_CONCRETE.key.toString() to Color.fromRGB(136, 30, 33),
        Material.YELLOW_CONCRETE.key.toString() to Color.fromRGB(222, 162, 19),
        Material.CRAFTING_TABLE.key.toString() to Color.fromRGB(33, 23, 57),
        Material.ENCHANTING_TABLE.key.toString() to Color.fromRGB(33, 23, 57),
        Material.SNOW.key.toString() to Color.fromRGB(232, 240, 239),
        Material.SNOW_BLOCK.key.toString() to Color.fromRGB(232, 240, 239)
    )

    for ((key, value) in defaultColors) {
        colors.addDefault(key, value)
    }
}